# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IMJtAnHU8MYd_RpZtm6KNb452SIT-aGJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from google.colab import files

uploaded = files.upload()

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.patches import Rectangle, FancyBboxPatch
from IPython.display import display

plt.rcParams.update({
    'figure.facecolor': 'white',
    'axes.facecolor': 'white',
    'axes.edgecolor': '#343a40',
    'axes.labelcolor': '#212529',
    'xtick.color': '#495057',
    'ytick.color': '#495057',
    'grid.color': '#dee2e6',
    'font.size': 11,
})

COLORS = {
    'blue': '#356bc4',
    'blue_light': '#b0cdff',
    'red': '#cc4343',
    'red_light': '#f5beb8',
    'green': '#248f5d',
    'green_light': '#b8e6cd',
    'amber': '#cf8e2d',
    'muted': '#5c6370',
    'grid': '#dee2e6',
    'ink': '#212529',
    'navy': '#0F1E46',
    'orange': '#F59E0B',
    'purple': '#9333EA',
    'gray_text': '#64748B',
    'grid': '#E5E7EB',
    'card_border': '#E5E7EB',
    'card_bg': '#FFFFFF'
}

plt.rcParams['font.family'] = 'DejaVu Sans'
plt.rcParams['axes.spines.top'] = False

fig = plt.figure(figsize=(18, 10), facecolor='white')

def finish_plot(fig, filename=None):
    fig.tight_layout()
    plt.show()

df = pd.read_excel('logins_db_for_assignment (1).xlsx')

print(df.shape)
df.head()

df.info()

df['successful_login'] = df['successful_login'].astype('Int64')
df['date'] = df['datetime'].dt.date
df['hour'] = df['datetime'].dt.hour
df['is_failure'] = df['successful_login'].eq(0)
df['is_success'] = df['successful_login'].eq(1)
df['is_off_hours'] = ~df['hour'].between(8, 18)
df['is_weekend'] = df['datetime'].dt.dayofweek >= 5
df.head()

df.describe()

df.isnull().sum()

PALETTE = {"safe": "#2ecc71", "warn": "#e67e22", "danger": "#e74c3c", "neutral": "#95a5a6", "blue": "#3498db"}
fig, axes = plt.subplots(1, 3, figsize=(14, 4))

outcome = df["successful_login"].map({1.0: "Success", 0.0: "Failure"}).value_counts()
axes[0].pie(outcome, labels=outcome.index, autopct="%1.1f%%",
            colors=[PALETTE["safe"], PALETTE["danger"]], startangle=90)
axes[0].set_title("Login Outcomes")

daily = df.groupby("date").size()
axes[1].bar(daily.index, daily.values, color=PALETTE["blue"], width=0.8)
axes[1].set_title("Daily Login Volume")
axes[1].set_xlabel("Date")
axes[1].tick_params(axis="x", rotation=45)

hourly = df.groupby("hour").size()
axes[2].bar(hourly.index, hourly.values, color=PALETTE["neutral"])
axes[2].set_title("Logins by Hour of Day")
axes[2].set_xlabel("Hour (UTC)")
axes[2].set_xticks(range(0, 24, 2))

plt.tight_layout()
plt.savefig("overview.png", bbox_inches="tight")
plt.show()

"""The dataset contains over 10,000 login events from January to March 2024. Each record includes the login time, user, IP address, device type, network type, and login outcome. The overall success rate is 93.8%, with login activity remaining relatively stable over time, except for several noticeable spikes in failed login attempts that warrant further investigation.

# Login Attempts — Security Anomaly Analysis
**Dataset:** `logins_db_for_assignment.xlsx` | 10,158 records | Jan–Mar 2024 | 100 users  
**Scope:** Part A — 5 anomaly investigations with visualisations | Part B — Enrichment recommendations + New-Accounts KPI dashboard
"""

df.shape

df['user'].nunique()

df['is_success'].sum()

df['is_failure'].sum()

df['successful_login'].isna().sum()

df['is_failure'].mean()

df.duplicated().sum()

# Daily attempts and failures
daily = (
    df.groupby('date')
      .agg(attempts=('user', 'size'), failures=('is_failure', 'sum'), successes=('is_success', 'sum'))
      .reset_index()
)
daily['date'] = pd.to_datetime(daily['date'])
daily

daily = daily.copy()
daily['failure_rate'] = daily['failures'] / daily['attempts'] * 100

total_attempts = int(daily['attempts'].sum())
total_failures = int(daily['failures'].sum())
overall_failure_rate = total_failures / total_attempts * 100
avg_attempts = daily['attempts'].mean()
avg_failures = daily['failures'].mean()

spike_date = pd.Timestamp('2024-02-09')
spike = daily.loc[daily['date'].eq(spike_date)].iloc[0]
spike_rate = spike['failure_rate']
avg_daily_failure_rate = daily['failure_rate'].mean()
spike_multiplier = spike_rate / avg_daily_failure_rate

daily['failure_rate'] = daily['failures'] / daily['attempts'] * 100
daily.head()

# Main title
fig.text(
    0.04, 0.94,
    'Daily Login Attempts and Failures',
    fontsize=24,
    weight='bold',
    color=COLORS['navy']
)

# KPI card
def draw_card(fig, x, y, w, h, title, value, subtitle, color):
    card = FancyBboxPatch(
        (x, y), w, h,
        boxstyle="round,pad=0.012,rounding_size=0.012",
        linewidth=1,
        edgecolor=COLORS['card_border'],
        facecolor=COLORS['card_bg'],
        transform=fig.transFigure,
        zorder=1
    )
    fig.patches.append(card)

    fig.text(x + 0.035, y + h - 0.035, title, fontsize=13, color=COLORS['gray_text'])
    fig.text(x + 0.035, y + h - 0.075, value, fontsize=22, weight='bold', color=color)
    fig.text(x + 0.035, y + 0.025, subtitle, fontsize=12, color=COLORS['gray_text'])

# KPI cards
card_y = 0.78
card_h = 0.11
card_w = 0.205
gap = 0.025
x0 = 0.04

draw_card(
    fig, x0, card_y, card_w, card_h,
    'Total Attempts',
    f'{total_attempts:,}',
    f'Avg / day: {avg_attempts:.0f}',
    COLORS['blue']
)

draw_card(
    fig, x0 + (card_w + gap), card_y, card_w, card_h,
    'Total Failures',
    f'{total_failures:,}',
    f'Avg / day: {avg_failures:.1f}',
    COLORS['red']
)

draw_card(
    fig, x0 + 2 * (card_w + gap), card_y, card_w, card_h,
    'Failure Rate (Overall)',
    f'{overall_failure_rate:.2f}%',
    f'Avg daily rate: {avg_daily_failure_rate:.2f}%',
    COLORS['orange']
)

draw_card(
    fig, x0 + 3 * (card_w + gap), card_y, card_w, card_h,
    'Date Range',
    f"{daily['date'].min():%b %d} – {daily['date'].max():%b %d, %Y}",
    f'{daily["date"].nunique()} days',
    COLORS['purple']
)

from matplotlib.patches import FancyBboxPatch
# Main chart
fig = plt.figure(figsize=(18, 10), facecolor='white')
ax = fig.add_axes([0.08, 0.18, 0.82, 0.52])
ax2 = ax.twinx()

# Bars
ax.bar(
    daily['date'],
    daily['attempts'],
    color=COLORS['blue_light'],
    label='Attempts',
    width=0.85,
    alpha=0.9
)

ax.bar(
    daily['date'],
    daily['failures'],
    color=COLORS['red'],
    label='Failures',
    width=0.85,
    alpha=0.9
)

# Failure rate line
ax2.plot(
    daily['date'],
    daily['failure_rate'],
    color=COLORS['navy'],
    marker='o',
    markersize=4,
    linewidth=2,
    label='Failure Rate (%)'
)

# Highlight spike
ax.axvline(
    spike['date'],
    color=COLORS['red'],
    linestyle='--',
    linewidth=1.5,
    alpha=0.5
)

ax.annotate(
    f"2024-02-09\n{int(spike['failures'])} failures / {int(spike['attempts'])} attempts\nFailure rate: {spike_rate:.1f}%",
    xy=(spike['date'], spike['attempts']),
    xytext=(spike['date'] + pd.Timedelta(days=5), spike['attempts'] + 35),
    arrowprops=dict(arrowstyle='-|>', color=COLORS['red'], lw=2),
    bbox=dict(boxstyle='round,pad=0.5', fc='#FFF5F5', ec=COLORS['red'], alpha=0.95),
    color=COLORS['red'],
    fontsize=12,
    weight='bold',
    ha='center'
)

# Axes formatting
ax.set_ylabel('Count', fontsize=13, color=COLORS['blue'], weight='bold')
ax2.set_ylabel('Failure Rate (%)', fontsize=13, color=COLORS['red'], weight='bold')

ax.tick_params(axis='y', colors=COLORS['blue'])
ax2.tick_params(axis='y', colors=COLORS['red'])

ax.grid(axis='y', color=COLORS['grid'], linewidth=1)
ax.set_axisbelow(True)

ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=1))
plt.setp(ax.get_xticklabels(), rotation=45, ha='right')

ax.set_ylim(0, max(daily['attempts']) * 1.25)
ax2.set_ylim(0, max(daily['failure_rate']) * 1.25)

# Legend
handles1, labels1 = ax.get_legend_handles_labels()
handles2, labels2 = ax2.get_legend_handles_labels()

fig.legend(
    handles1 + handles2,
    labels1 + labels2,
    loc='upper left',
    bbox_to_anchor=(0.08, 0.74),
    ncol=3,
    frameon=False,
    fontsize=12
)

"""Most days are very stable:
- 140-180 attempts/day

This suggests:
-Normal user activity
-No large traffic spikes
-No evidence of a mass registration event
-No major outage causing repeated retries

The baseline is fairly consistent.

Most days we see consistant:
- 5-15 failures/day (~3-8% failure rate)

The obvious anomaly is:

Date: 2024-02-09

- 259 attempts
- 96 failures

Failure rate = 37.1%

Compared to normal:
- 150 attempts
- 7 failures

Failure rate = 4-5%
"""

df['date'] = pd.to_datetime(df['date'])
feb9 = df[df['date'] == '2024-02-09']

print(feb9.shape)
feb9.head()

(
    feb9[feb9['is_failure']]
    .groupby('user')
    .size()
    .sort_values(ascending=False)
    .head(20)
)

(
    feb9.groupby('ip')
    .agg(
        attempts=('user', 'size'),
        failures=('is_failure', 'sum'),
        users=('user', 'nunique')
    )
    .sort_values('failures', ascending=False)
    .head(10)
)

##top suspisious users by date
nightly_probe_candidates = (
    df[df['is_failure']]
    .groupby(['user', 'ip', 'date'])
    .agg(
        failed_attempts=('datetime', 'count'),
        first_seen=('datetime', 'min'),
        last_seen=('datetime', 'max'),
        active_days=('date', 'nunique'),
        unique_dates=('date', lambda x: sorted(x.unique()))
    )
    .reset_index()
)
nightly_probe_candidates = nightly_probe_candidates.sort_values(
    ['active_days', 'failed_attempts'],
    ascending=False
)

nightly_probe_candidates.head(20)

##top suspisious all time
user_summary = (
    df.groupby('user')
      .agg(
          total_attempts=('datetime', 'count'),
          unique_ips=('ip', 'nunique'),
          failed_logins=('is_failure', 'sum'),
          successful_logins=('is_success', 'sum'),
          first_seen=('datetime', 'min'),
          last_seen=('datetime', 'max')
      )
      .reset_index()
)

user_summary['failure_rate'] = (
    user_summary['failed_logins']
    / user_summary['total_attempts']
    * 100
).round(2)

user_summary.sort_values(
    ['failed_logins', 'unique_ips'],
    ascending=False
).head(20)

##top suspisious ips all time
user_summary = (
    df.groupby('ip')
      .agg(
          total_attempts=('datetime', 'count'),
          user=('user', 'nunique'),
          failed_logins=('is_failure', 'sum'),
          successful_logins=('is_success', 'sum'),
          first_seen=('datetime', 'min'),
          last_seen=('datetime', 'max')
      )
      .reset_index()
)

user_summary['failure_rate'] = (
    user_summary['failed_logins']
    / user_summary['total_attempts']
    * 100
).round(2)

user_summary.sort_values(
    ['failed_logins', 'user'],
    ascending=False
).head(20)

user_ip_summary = (
    df.groupby(['user', 'ip'])
      .agg(
          attempts=('datetime', 'count'),
          failures=('is_failure', 'sum'),
          successes=('is_success', 'sum'),
          first_seen=('datetime', 'min'),
          last_seen=('datetime', 'max'),
          active_days=('date', 'nunique')
      )
      .reset_index()
)

user_ip_summary['failure_rate'] = (
    user_ip_summary['failures']
    / user_ip_summary['attempts']
    * 100
).round(2)

user_ip_summary.sort_values(
    ['failures', 'attempts'],
    ascending=False
).head(20)

ip_user_summary = (
    df.groupby('ip')
      .agg(
          total_attempts=('datetime', 'count'),
          unique_users=('user', 'nunique'),
          failures=('is_failure', 'sum'),
          successes=('is_success', 'sum'),
          active_days=('date', 'nunique'),
          first_seen=('datetime', 'min'),
          last_seen=('datetime', 'max')
      )
      .reset_index()
)

ip_user_summary['failure_rate'] = (
    ip_user_summary['failures']
    / ip_user_summary['total_attempts']
    * 100
).round(2)

ip_user_summary.sort_values(
    ['unique_users', 'failures'],
    ascending=False
).head(20)

df["successful_login"] = df["successful_login"].fillna(0)
failures=(df["successful_login"] == 0).astype(int), "sum"
user_stats = (
    df.groupby("user")
      .agg(
          total=("user", "count"),
          unique_ips=("ip", "nunique"),
          failures=("is_failure", "sum")
      )
      .reset_index()
)

user_stats["fail_rate"] = user_stats["failures"] / user_stats["total"]
user_stats["ip_velocity"] = user_stats["unique_ips"] / user_stats["total"]


user_stats

user_stats["suspicion_score"] = (
    user_stats["failures"]
    * user_stats["ip_velocity"]
)

user_stats.sort_values(
    "suspicion_score",
    ascending=False
).head(20)

flagged = user_stats[(user_stats["ip_velocity"] > 0.6) | (user_stats["fail_rate"] > 0.3)]
flagged

"""To identify potentially suspicious accounts, two behavioral indicators were calculated:

Failure Rate (fail_rate) – the percentage of login attempts that resulted in authentication failures.
IP Velocity (ip_velocity) – the ratio of unique IP addresses to total login attempts, measuring how frequently a user changes source IPs.

Users were flagged when either:

fail_rate > 30%
ip_velocity > 0.6


A high failure rate may indicate password guessing, credential stuffing, account takeover attempts, or users repeatedly entering incorrect credentials.

A high IP velocity suggests that a user is logging in from an unusually large number of different IP addresses relative to their activity volume. This behavior may be associated with VPN usage, proxy rotation, automated scripts, account sharing, or compromised credentials.

The selected thresholds are intended as anomaly-detection heuristics rather than strict fraud rules. They help narrow the investigation to accounts whose behavior significantly deviates from typical user login patterns and therefore warrant further review.

#Case 1
"""

u97 = df[df["user"] == "user_097"].copy()
u97["failed"]  = (u97["successful_login"] == 0).astype(int)

u97

daily_fails = u97.groupby("date")["failed"].sum().reset_index()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

colors = [PALETTE["danger"] if str(d) == "2024-02-09" else PALETTE["warn"] for d in daily_fails["date"]]
axes[0].bar(daily_fails["date"], daily_fails["failed"], color=colors, width=0.8)
axes[0].set_title("user_097 — Daily Failed Logins", fontweight="bold")
axes[0].set_xlabel("Date")
axes[0].set_ylabel("Failed Attempts")
axes[0].tick_params(axis="x", rotation=45)
axes[0].annotate("Burst: 48 fails\nat same second",
                 xy=(pd.Timestamp("2024-02-09"), 48), xytext=(pd.Timestamp("2024-02-15"), 40),
                 arrowprops=dict(arrowstyle="->", color="black"), fontsize=9, color="darkred")

top_ips = u97["ip"].value_counts().head(10).index
ip_stats = u97[u97["ip"].isin(top_ips)].groupby("ip")["failed"].agg(["sum", "count"]).rename(columns={"sum": "Failures", "count": "Total"})
ip_stats["Successes"] = ip_stats["Total"] - ip_stats["Failures"]
ip_stats = ip_stats.sort_values("Failures", ascending=True)
axes[1].barh(ip_stats.index, ip_stats["Failures"], color=PALETTE["danger"], label="Failures")
axes[1].barh(ip_stats.index, ip_stats["Successes"], left=ip_stats["Failures"], color=PALETTE["safe"], label="Successes")
axes[1].set_title("user_097 — Top 10 IPs: Success vs Failure", fontweight="bold")
axes[1].set_xlabel("Login Count")
axes[1].legend()

plt.tight_layout()
plt.savefig("anomaly1_brute_force.png", bbox_inches="tight")
plt.show()

burst = df[(df["user"] == "user_097") & (df["datetime"] == "2024-02-09 18:24:00")]
print(f"Total logins: {len(u97)} | Failed: {u97.failed.sum()} ({u97.failed.mean():.0%}) | Unique IPs: {u97.ip.nunique()}")
print(f"Burst event (2024-02-09 18:24): {len(burst)} attempts in same second")

case1 = df[(df['user'].eq('user_097')) & (df['ip'].eq('103.56.23.138')) &
           (df['datetime'].between('2024-02-09 18:24:00', '2024-02-09 18:24:01'))].copy()

case1_summary = pd.Series({
    'attempts': len(case1),
    'failures': int(case1['is_failure'].sum()),
    'successes': int(case1['is_success'].sum()),
    'unique_users': case1['user'].nunique(),
    'unique_ips': case1['ip'].nunique(),
    'first_seen': case1['datetime'].min(),
    'last_seen': case1['datetime'].max(),
})

per_second = (
    case1.groupby('datetime')
         .agg(failures=('is_failure', 'sum'), successes=('is_success', 'sum'), attempts=('user', 'size'))
         .reset_index()
)

fig, ax = plt.subplots(figsize=(10.5, 5.2))
x = np.arange(len(per_second))
ax.bar(x, per_second['failures'], color=COLORS['red'], label='Failures')
ax.bar(x, per_second['successes'], bottom=per_second['failures'], color=COLORS['green'], label='Successes')
ax.set_xticks(x)
ax.set_xticklabels(per_second['datetime'].dt.strftime('%H:%M:%S'))
ax.set_ylabel('Attempts')
ax.set_title('user_097: 93 attempts from one IP in two seconds', fontsize=16, weight='bold', loc='left')
for i, row in per_second.iterrows():
    ax.text(i, row['attempts'] + 1, f"{int(row['attempts'])} attempts", ha='center', weight='bold')
ax.legend(frameon=False)
finish_plot(fig, 'user097_two_second_burst.png')

"""Anomaly 1 — Brute-Force Burst: user_097
Red flag: On 2024-02-09 at 18:24:00, 48 failed login attempts were recorded for user_097 from the same IP 103.56.23.138 at the exact same timestamp — physically impossible for a human user. This is a textbook automated credential-stuffing or brute-force attack burst. Across the full dataset user_097 accumulated 97 failures out of 194 logins (50% failure rate).

#Case 2
"""

u3 = df[df["user"] == "user_003"].copy()
u3["date_str"] = u3["datetime"].dt.strftime("%m-%d")
u3["failed"]  = (u3["successful_login"] == 0).astype(int)
u3_fails = u3[u3["failed"] == 1].copy()

pivot = u3.pivot_table(index="hour", columns="date_str", values="failed", aggfunc="sum").fillna(0)

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

sns.heatmap(pivot, ax=axes[0], cmap="Reds", linewidths=0.3, cbar_kws={"label": "Failed Logins"})
axes[0].set_title("user_003 — Failed Logins by Hour x Date", fontweight="bold")
axes[0].set_xlabel("Date (MM-DD)")
axes[0].set_ylabel("Hour of Day")
axes[0].tick_params(axis="x", rotation=90, labelsize=7)

nightly = u3_fails[u3_fails["ip"] == "142.147.67.230"]
other_fails = u3_fails[u3_fails["ip"] != "142.147.67.230"]
axes[1].scatter(other_fails["datetime"], other_fails["hour"], c=PALETTE["warn"], s=40, label="Other failures", alpha=0.7)
axes[1].scatter(nightly["datetime"], nightly["hour"], c=PALETTE["danger"], s=60, marker="x",
                linewidths=2, label=f"Nightly probe (142.147.67.230) — {len(nightly)} events")
axes[1].axhline(20, color="red", linestyle="--", linewidth=1, alpha=0.5, label="20:00 line")
axes[1].set_title("user_003 — All Failed Logins Timeline", fontweight="bold")
axes[1].set_xlabel("Date")
axes[1].set_ylabel("Hour of Day")
axes[1].legend(fontsize=8)
axes[1].tick_params(axis="x", rotation=45)

plt.tight_layout()
plt.savefig("anomaly2_nightly_probe.png", bbox_inches="tight")
plt.show()

print(f"Nightly probe events at exactly 20:00 from 142.147.67.230: {len(nightly)}")
print(f"Consecutive daily cadence: {nightly.date.min()} to {nightly.date.max()}")

case2 = df[(df['user'].eq('user_003')) & (df['ip'].eq('142.147.67.230'))].sort_values('datetime').copy()
case2_summary = pd.Series({
    'attempts': len(case2),
    'failures': int(case2['is_failure'].sum()),
    'successes': int(case2['is_success'].sum()),
    'first_seen': case2['datetime'].min(),
    'last_seen': case2['datetime'].max(),
    'unique_hours': sorted(case2['hour'].unique().tolist()),
})
display(case2_summary)
display(case2[['datetime', 'user', 'ip', 'device_type', 'network_type', 'successful_login']].tail())

fig, ax = plt.subplots(figsize=(14, 3.6))
colors = case2['successful_login'].map({0: COLORS['red'], 1: COLORS['green']}).fillna(COLORS['amber'])
ax.scatter(case2['datetime'], np.ones(len(case2)), s=180, marker='s', color=colors)
ax.set_yticks([])
ax.set_title('user_003: one 20:00 attempt per day; 32 failures then success', fontsize=16, weight='bold', loc='left')
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
ax.grid(axis='x', alpha=0.6)
ax.scatter([], [], s=120, marker='s', color=COLORS['red'], label='Failed login')
ax.scatter([], [], s=120, marker='s', color=COLORS['green'], label='Successful login')
ax.legend(frameon=False, loc='upper left')
finish_plot(fig, 'user003_low_and_slow.png')

"""Anomaly 2 — Automated Nightly Probe: user_003
Red flag: user_003 received a failed login every single day at exactly 20:00:00 from the same IP 142.147.67.230 for 33 consecutive days (Jan 2 – Feb 2, 2024). This machine-precision regularity is impossible for human behaviour — it indicates a scheduled script or bot persistently probing this account on a fixed cron interval. user_003 also logged 93 unique IPs across 134 sessions.

#Case 3
"""

event = df[df["ip"] == "45.139.113.61"].copy()
event["failed"]  = (event["successful_login"] == 0).astype(int)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

event_sorted = event.sort_values("successful_login", ascending=False)
bar_colors = [PALETTE["safe"] if s == 1.0 else PALETTE["danger"] for s in event_sorted["successful_login"]]
axes[0].barh(event_sorted["user"], [1] * len(event_sorted), color=bar_colors)
axes[0].set_title(f"20 Users from IP {shared_ip}\nat identical timestamp 2024-03-14 12:05:00", fontweight="bold")
axes[0].set_xlabel("Login attempt (1 per user)")
axes[0].legend(handles=[
    plt.Rectangle((0,0),1,1, fc=PALETTE["safe"],   label="Success"),
    plt.Rectangle((0,0),1,1, fc=PALETTE["danger"], label="Failure")
], loc="lower right")

ip_user_count = df.groupby("ip")["user"].nunique().sort_values(ascending=False).head(15)
bar_c2 = [PALETTE["danger"] if ip == shared_ip else PALETTE["neutral"] for ip in ip_user_count.index]
axes[1].bar(range(len(ip_user_count)), ip_user_count.values, color=bar_c2)
axes[1].set_xticks(range(len(ip_user_count)))
axes[1].set_xticklabels(ip_user_count.index, rotation=45, ha="right", fontsize=8)
axes[1].set_title("Top IPs by Unique User Count", fontweight="bold")
axes[1].set_ylabel("Distinct Users")
axes[1].annotate("Anomaly IP", xy=(0, 20), xytext=(3, 18),
                 arrowprops=dict(arrowstyle="->"), fontsize=9, color="darkred")

plt.tight_layout()
plt.savefig("anomaly3_shared_ip.png", bbox_inches="tight")
plt.show()

print(f"Users on IP {shared_ip}: {event.user.nunique()}")
print(f"Unique timestamps: {event.datetime.nunique()} — all at: {event.datetime.iloc[0]}")
print(f"Success: {int(event.successful_login.sum())} | Failure: {int(event.failed.sum())}")

case3 = df[df['ip'].eq('45.139.113.61')].sort_values(['successful_login', 'user'], ascending=[False, True]).copy()
case3_summary = pd.Series({
    'attempts': len(case3),
    'distinct_users': case3['user'].nunique(),
    'failures': int(case3['is_failure'].sum()),
    'successes': int(case3['is_success'].sum()),
    'first_seen': case3['datetime'].min(),
    'last_seen': case3['datetime'].max(),
})
display(case3_summary)
display(case3[['datetime', 'user', 'ip', 'device_type', 'network_type', 'successful_login']])

# Helpful cross-check: exact timestamp groups in the whole dataset
timestamp_groups = (
    df.groupby('datetime')
      .agg(attempts=('user', 'size'), users=('user', 'nunique'), ips=('ip', 'nunique'), failures=('is_failure', 'sum'), successes=('is_success', 'sum'))
      .sort_values(['attempts', 'users'], ascending=False)
)
display(timestamp_groups.head(10))

fig, ax = plt.subplots(figsize=(12, 6))
y = np.arange(len(case3))
bar_colors = case3['successful_login'].map({1: COLORS['green_light'], 0: COLORS['red_light']}).fillna(COLORS['amber'])
edge_colors = case3['successful_login'].map({1: COLORS['green'], 0: COLORS['red']}).fillna(COLORS['amber'])
ax.barh(y, np.ones(len(case3)), color=bar_colors, edgecolor=edge_colors, linewidth=2)
ax.set_yticks(y)
ax.set_yticklabels(case3['user'])
ax.set_xticks([])
ax.invert_yaxis()
ax.set_title('IP 45.139.113.61: 20 users at the exact same timestamp', fontsize=16, weight='bold', loc='left')
for idx, row in enumerate(case3.itertuples()):
    label = 'success' if row.successful_login == 1 else 'failed'
    color = COLORS['green'] if row.successful_login == 1 else COLORS['red']
    ax.text(0.04, idx, label, va='center', color=color, weight='bold')
finish_plot(fig, 'ip45_multi_user_spray.png')

"""---
## Anomaly 3 — Mass Simultaneous Logins from Single IP: `45.139.113.61`
**Red flag:** On 2024-03-14 at 12:05:00, **20 distinct users** all logged in from the **same IP address** at the **exact same second**. This is physically impossible for legitimate use — a single IP cannot simultaneously authenticate 20 different sessions in the same instant. This strongly suggests a **shared proxy, VPN exit node, or automated botnet controller** executing a coordinated replay or session-injection attack. 5 of the 20 attempts failed, suggesting partial account compromise.

#Case 4
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

normal = user_stats[~user_stats["user"].isin(flagged["user"])]
axes[0].scatter(normal["ip_velocity"],  normal["fail_rate"],  c=PALETTE["blue"],   s=50,  alpha=0.6, label="Normal")
axes[0].scatter(flagged["ip_velocity"], flagged["fail_rate"], c=PALETTE["danger"], s=100, zorder=5,  label="Flagged")
for _, row in flagged.iterrows():
    axes[0].annotate(row["user"], (row["ip_velocity"], row["fail_rate"]),
                     fontsize=7, ha="left", color="darkred")
axes[0].axvline(0.6, color="orange", linestyle="--", linewidth=1, label="Threshold 0.6")
axes[0].axhline(0.3, color="red",    linestyle="--", linewidth=1, label="Threshold 0.3")
axes[0].set_xlabel("IP Velocity (unique IPs / total logins)")
axes[0].set_ylabel("Failure Rate")
axes[0].set_title("User Risk Matrix — IP Velocity vs Failure Rate", fontweight="bold")
axes[0].legend(fontsize=8)

top15 = user_stats.nlargest(15, "unique_ips")
bar_c = [PALETTE["danger"] if u in flagged["user"].values else PALETTE["blue"] for u in top15["user"]]
axes[1].barh(top15["user"], top15["unique_ips"], color=bar_c)
axes[1].set_title("Top 15 Users by Unique IP Count", fontweight="bold")
axes[1].set_xlabel("Unique IPs")

plt.tight_layout()
plt.savefig("anomaly4_ip_velocity.png", bbox_inches="tight")
plt.show()

print(f"Flagged users: {len(flagged)}")

"""Anomaly 4 — Extreme IP Velocity (Botnet / Credential Stuffing)
Red flag: Several users exhibit an abnormally high number of unique source IPs per session count, far beyond what is explainable by VPNs or travel. user_003 used 93 distinct IPs across 134 logins (0.69 IPs/login). This pattern is the hallmark of a distributed botnet credential-stuffing campaign where each attempt originates from a different compromised host to evade rate-limiting and IP-based blocks.

#Case 5
"""

heatmap_data = df.groupby(["user", "hour"]).size().unstack(fill_value=0)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

sns.heatmap(heatmap_data, ax=axes[0], cmap="Blues", linewidths=0.1,
            xticklabels=range(24), yticklabels=True, cbar_kws={"label": "Login Count"})
axes[0].set_title("All Users — Login Count by Hour of Day", fontweight="bold")
axes[0].set_xlabel("Hour of Day")
axes[0].set_ylabel("User")
axes[0].tick_params(axis="y", labelsize=6)
axes[0].axvspan(0, 5, alpha=0.15, color="red", label="Off-hours (00-05)")

hourly_total = df.groupby("hour").size()
bar_cols = [PALETTE["danger"] if h < 6 else PALETTE["blue"] for h in hourly_total.index]
axes[1].bar(hourly_total.index, hourly_total.values, color=bar_cols, width=0.8)
axes[1].set_title("Total Logins by Hour — Off-Hours Highlighted", fontweight="bold")
axes[1].set_xlabel("Hour of Day")
axes[1].set_ylabel("Login Count")
axes[1].set_xticks(range(0, 24))
axes[1].legend(handles=[
    plt.Rectangle((0,0),1,1, fc=PALETTE["danger"], label="Off-hours (00-05)"),
    plt.Rectangle((0,0),1,1, fc=PALETTE["blue"],   label="Business hours")
])

plt.tight_layout()
plt.savefig("anomaly5_offhours.png", bbox_inches="tight")
plt.show()

offhours = df[df["hour"] < 6]
print(f"Off-hours logins total: {len(offhours)}")
print(offhours[["datetime","user","ip","successful_login"]].sort_values("datetime").to_string(index=False))

"""Anomaly 5 — Off-Hours Logins (00:00–05:00)
Red flag: The vast majority of logins occur between 07:00–22:00, consistent with normal business hours. However, user_009 generated 4 logins between midnight and 5am — uncommon for a legitimate user. Combined with user_009's 89 unique IPs and appearance in the mass simultaneous event (Anomaly 3), these off-hours sessions suggest either a compromised account accessed by an attacker in a different timezone, or an automated script running overnight.
"""

quality = df[
    df[['ip', 'device_type', 'network_type', 'successful_login']].isna().any(axis=1)
    | df['device_type'].eq('desktop computer')
    | df['network_type'].eq('home wifi')
].copy()

quality_counts = pd.Series({
    'Missing IP': int(df['ip'].isna().sum()),
    'Missing device_type': int(df['device_type'].isna().sum()),
    'Missing network_type': int(df['network_type'].isna().sum()),
    'Missing successful_login': int(df['successful_login'].isna().sum()),
    'Non-standard device label': int(df['device_type'].eq('desktop computer').sum()),
    'Non-standard network label': int(df['network_type'].eq('home wifi').sum()),
})
display(quality[['datetime', 'user', 'ip', 'device_type', 'network_type', 'successful_login']])

fig, ax = plt.subplots(figsize=(11, 4.8))
quality_counts.sort_values().plot(kind='barh', ax=ax, color=COLORS['amber'])
ax.set_title('Log integrity issues', fontsize=16, weight='bold', loc='left')
ax.set_xlabel('Rows')
for i, value in enumerate(quality_counts.sort_values()):
    ax.text(value + 0.05, i, int(value), va='center', weight='bold')
finish_plot(fig, 'log_integrity_issues.png')

"""---
## Part 2 — Question 1: Additional Data Fields & Patterns


"""

from plotly.subplots import make_subplots
import plotly.graph_objects as go

dates = pd.date_range("2024-01-01", periods=90, freq="D")
base  = 120
trend = np.linspace(0, 20, 90)
noise = np.random.normal(0, 15, 90)
surge = np.zeros(90)
surge[83:] = np.array([60, 80, 190, 220, 210, 200, 195])

signups   = np.maximum(0, base + trend + noise + surge).astype(int)
verified  = (signups * np.clip(np.random.normal(0.78, 0.05, 90), 0.5, 1.0)).astype(int)
activated = (verified * np.clip(np.random.normal(0.55, 0.08, 90), 0.3, 0.8)).astype(int)
paid_pct  = np.clip(np.random.normal(0.30, 0.04, 90), 0.1, 0.6)
paid_pct[83:] = np.clip(paid_pct[83:] * 0.6, 0.1, 0.6)

organic  = (signups * np.clip(np.random.normal(0.40, 0.05, 90), 0.2, 0.7)).astype(int)
paid_ch  = (signups * np.clip(np.random.normal(0.25, 0.04, 90), 0.1, 0.5)).astype(int)
referral = (signups * np.clip(np.random.normal(0.20, 0.04, 90), 0.05, 0.4)).astype(int)
direct   = np.maximum(0, signups - organic - paid_ch - referral)

geo_labels = ["US", "EU", "APAC", "LATAM", "Other"]
geo_pre    = [40, 25, 18, 10, 7]
geo_surge  = [30, 18, 12, 8, 32]

df_kpi = pd.DataFrame({
    "date": dates, "signups": signups, "verified": verified, "activated": activated,
    "paid_pct": paid_pct, "organic": organic, "paid": paid_ch, "referral": referral, "direct": direct
})
df_kpi["verify_rate"]   = df_kpi["verified"]  / df_kpi["signups"]
df_kpi["activate_rate"] = df_kpi["activated"] / df_kpi["verified"].replace(0, np.nan)
df_kpi["7d_avg"]        = df_kpi["signups"].rolling(7).mean()

SURGE_START = pd.Timestamp("2024-03-25")

fig = make_subplots(
    rows=3, cols=2,
    subplot_titles=(
        "Daily Sign-ups with 7-Day Rolling Avg",
        "Acquisition Channel Mix",
        "Funnel Conversion Rates",
        "Geographic Distribution: Pre-Surge vs Surge Week",
        "Account Quality Rates (7d rolling)",
        "Paid Conversion Rate (quality proxy)"
    ),
    specs=[
        [{"type": "xy"}, {"type": "xy"}],
        [{"type": "xy"}, {"type": "xy"}],
        [{"type": "xy"}, {"type": "xy"}],
    ],
    vertical_spacing=0.12, horizontal_spacing=0.10
)

# Panel 1: daily signups
bar_colors = ["#e74c3c" if d >= SURGE_START else "#3498db" for d in df_kpi.date]
fig.add_trace(go.Bar(x=df_kpi.date, y=df_kpi.signups, name="Daily Sign-ups",
                     marker_color=bar_colors, showlegend=True), row=1, col=1)
fig.add_trace(go.Scatter(x=df_kpi.date, y=df_kpi["7d_avg"], name="7-Day Avg",
                          line=dict(color="#f39c12", width=2), showlegend=True), row=1, col=1)
fig.add_vrect(x0=str(SURGE_START.date()), x1=str(df_kpi.date.max().date()),
              fillcolor="rgba(231,76,60,0.08)", line_width=0, row=1, col=1)

# Panel 2: channel mix
for ch, col in [("organic","#3498db"),("paid","#e74c3c"),("referral","#2ecc71"),("direct","#95a5a6")]:
    fig.add_trace(go.Bar(x=df_kpi.date, y=df_kpi[ch], name=ch.capitalize(),
                         marker_color=col, showlegend=True), row=1, col=2)

# Panel 3: funnel rates
fig.add_trace(go.Scatter(x=df_kpi.date, y=df_kpi.verify_rate, name="Email Verify Rate",
                          line=dict(color="#3498db", width=2), showlegend=False), row=2, col=1)
fig.add_trace(go.Scatter(x=df_kpi.date, y=df_kpi.activate_rate, name="Activation Rate",
                          line=dict(color="#2ecc71", width=2), showlegend=False), row=2, col=1)
fig.add_vrect(x0=str(SURGE_START.date()), x1=str(df_kpi.date.max().date()),
              fillcolor="rgba(231,76,60,0.08)", line_width=0, row=2, col=1)

# Panel 4: geo grouped bar comparison (pre-surge vs surge week)
fig.add_trace(go.Bar(name="Pre-Surge %", x=geo_labels, y=geo_pre,
                     marker_color="#3498db", showlegend=True), row=2, col=2)
fig.add_trace(go.Bar(name="Surge Week %", x=geo_labels, y=geo_surge,
                     marker_color="#e74c3c", showlegend=True), row=2, col=2)

# Panel 5: quality rates
fig.add_trace(go.Scatter(x=df_kpi.date, y=df_kpi.verify_rate.rolling(7).mean(),
                          name="Verify Rate (7d)", line=dict(color="#3498db", width=2)), row=3, col=1)
fig.add_trace(go.Scatter(x=df_kpi.date, y=df_kpi.activate_rate.rolling(7).mean(),
                          name="Activate Rate (7d)", line=dict(color="#2ecc71", width=2)), row=3, col=1)
fig.add_vrect(x0=str(SURGE_START.date()), x1=str(df_kpi.date.max().date()),
              fillcolor="rgba(231,76,60,0.08)", line_width=0, row=3, col=1)

# Panel 6: paid conversion
fig.add_trace(go.Scatter(x=df_kpi.date, y=df_kpi.paid_pct, fill="tozeroy", name="Paid Conv. Rate",
                          line=dict(color="#e74c3c", width=1.5),
                          fillcolor="rgba(231,76,60,0.2)"), row=3, col=2)
fig.add_vrect(x0=str(SURGE_START.date()), x1=str(df_kpi.date.max().date()),
              fillcolor="rgba(231,76,60,0.08)", line_width=0, row=3, col=2)

fig.update_layout(
    barmode="stack",
    height=1000,
    title_text="<b>New Customer Sign-Ups — KPI Monitoring Dashboard</b><br>"
               "<sup>Red shading = surge period (Mar 25+) | Note quality drop-off during spike</sup>",
    title_font_size=16,
    font=dict(family="Arial"),
    paper_bgcolor="white",
    plot_bgcolor="#f8f9fa",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
)

fig.write_html("signup_kpi_dashboard.html", full_html=True, include_plotlyjs="cdn")
print("Dashboard saved: signup_kpi_dashboard.html")
fig.show()

"""### Additional Fields That Would Improve Detection

| Field | Why it helps |
|---|---|
| **Geolocation (country / city / ASN)** | Detect impossible travel; flag logins from known malicious ASNs or Tor exit nodes |
| **User-Agent / Browser fingerprint** | Bots reuse identical or absent UA strings; mismatches between device_type and UA reveal spoofing |
| **Session duration** | Legitimate users browse for minutes; bots often disconnect within seconds of a successful login |
| **Failure reason code** | Distinguish wrong-password from locked-account from MFA-fail — brute force shows wrong-password; stuffing shows distributed wrong-password across many accounts |
| **MFA status / step-up events** | Accounts that bypass MFA or trigger MFA challenges abnormally often are high-priority targets |
| **Account age at login time** | Very new accounts attempting high-privilege actions immediately after creation are suspicious |
| **Previous login baseline (typical hour/day/IP)** | Enables deviation scoring: flag sessions that deviate significantly from a user's own historical baseline |

### Additional Suspicious Patterns to Monitor

1. **Impossible travel** — same user authenticated from two geographically distant IPs within a window too short to travel between them
2. **Password-spray pattern** — low failure rate per user but one IP cycling across hundreds of accounts (opposite of brute force)
3. **Account takeover post-login** — successful login followed immediately by password change, email update, or large data export
4. **New device + new IP + off-hours** — triple-novelty logins with no prior fingerprint are the highest-risk session class
5. **Dormant account sudden activity** — accounts inactive 30+ days suddenly logging in from a new IP/device combination
6. **Velocity per subnet (/24)** — aggregate by subnet to detect distributed attacks that rotate IPs within the same range (as seen with `103.56.23.*` for user_097)

## Summary of Findings

| # | Anomaly | Severity | Detail |
|---|---|---|---|
| 1 | Brute-force burst | Critical | `user_097` — 48 attempts/second on 2024-02-09 |
| 2 | Automated nightly probe | Critical | `user_003` — 33 consecutive days at exact 20:00 |
| 3 | Mass simultaneous logins | Critical | 20 users from single IP at identical timestamp |
| 4 | Botnet credential stuffing | High | 5+ users with >60% IP velocity |
| 5 | Off-hours access | Medium | `user_009` — 4 logins between 00:00–05:00 |

**Recommended immediate actions:**
- Block IPs `45.139.113.61` and `142.147.67.230`
- Force password reset for `user_097` and `user_003`
- Rate-limit logins to 5 attempts/minute per user
- Enable geo-velocity checks and MFA enforcement
"""